options:
  max-time: 15

pipelines:
  default:
    - step:
        name: Tests
        image: python:3.6
        caches:
            - pip
        script:
            - make install-pipeline
            - make test
