name: CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: Setup, Lint & Test Leukeleu Django GDPR
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup
        uses: ./.github/actions/python-setup
      - name: Lint
        uses: ./.github/actions/python-lint
      - name: Test
        uses: ./.github/actions/python-test
